glb=/.config/Code/User/settings.json
python=/.config/Code/User/profiles/-2b17963a/settings.json
rust=/.config/Code/User/profiles/-35997400/settings.json
cpp=/.config/Code/User/profiles/-6b5cd3db/settings.json
java=/.config/Code/User/profiles/-3891810/settings.json
latex=/.config/Code/User/profiles/4b3b38ba/settings.json